development:
  database: full_circle
  adapter: postgresql
  host: localhost
  port: 5432
  username: full_circle 
  password: nyhlisted
  encoding: utf8

test:
  database: full_circle_test
  adapter: postgresql
  host: localhost
  port: 5432
  username: full_circle 
  password: nyhlisted
  encoding: utf8

production:
  database: full_circle
  adapter: postgresql
  host: localhost
  port: 5432
  username: full_circle
  password: nyhlisted
  encoding: utf8
