class AddIndustryCodeToProduct < ActiveRecord::Migration
  def change
    add_column :products, :industry_code, :string
    Product.where(name1: "Oil Palm Fruit").update_all(industry_code: "01261")
    Product.where(name1: "Large Pig unweighted").update_all(industry_code: "01450")
    Product.where(name1: "Small Pig unweighted").update_all(industry_code: "01450")
    Product.where(name1: "Large Pig").update_all(industry_code: "01450")
    Product.where(name1: "Retired Boar").update_all(industry_code: "01450")
    Product.where(name1: "Retired Boar unweighted").update_all(industry_code: "01450")
    Product.where(name1: "Retired Sow").update_all(industry_code: "01450")
    Product.where(name1: "Duroc Gilt").update_all(industry_code: "01450")
    Product.where(name1: "Retired Sow unweighted").update_all(industry_code: "01450")
    Product.where(name1: "Female Duroc").update_all(industry_code: "01450")
    Product.where(name1: "Boar").update_all(industry_code: "01450")
    Product.where(name1: "Second Grade Pig").update_all(industry_code: "01450")
    Product.where(name1: "Mid Size Pig").update_all(industry_code: "01450")
    Product.where(name1: "Male Duroc").update_all(industry_code: "01450")
    Product.where(name1: "Small Pig").update_all(industry_code: "01450")
    Product.where(name1: "Medium Pig unweighted").update_all(industry_code: "01450")
    Product.where(name1: "Small Pig Extra Charges").update_all(industry_code: "01450")
    Product.where(name1: "Egg Grade Broken").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade A").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade AA").update_all(industry_code: "01466")
    Product.where(name1: "Telur Pidan").update_all(industry_code: "01466")
    Product.where(name1: "Salted Duck Egg").update_all(industry_code: "01466")
    Product.where(name1: "Liquid Egg").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade White").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade G").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade F").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade Crack").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade C").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade B").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade E").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade Dirty").update_all(industry_code: "01466")
    Product.where(name1: "Egg Grade D").update_all(industry_code: "01466")
    Product.where(name1: "Strater (Hisex)").update_all(industry_code: "01466")
    Product.where(name1: "Partin Fish").update_all(industry_code: "03221")
    Product.where(name1: "AA-Tray").update_all(industry_code: "46696")
    Product.where(name1: "Egg Tray").update_all(industry_code: "46696")
    Product.where(name1: "Uni-Tray").update_all(industry_code: "46696")
    Product.where(name1: "Fencols 4%").update_all(industry_code: "4690")
    Product.where(name1: "Veterimoxin LA Clas").update_all(industry_code: "4690")
    Product.where(name1: "Amprol 12%").update_all(industry_code: "4690")
    Product.where(name1: "Colistin Sulphate 10%").update_all(industry_code: "4690")
    Product.where(name1: "Colmyc-E(SP)").update_all(industry_code: "4690")
    Product.where(name1: "TM-200").update_all(industry_code: "4690")
    Product.where(name1: "Denagard 10% Coated").update_all(industry_code: "4690")
    Product.where(name1: "Tiotilin").update_all(industry_code: "4690")
    Product.where(name1: "CTC").update_all(industry_code: "4690")
    Product.where(name1: "FlorCol Injection").update_all(industry_code: "4690")
    Product.where(name1: "ENRO 0.5%").update_all(industry_code: "4690")
    Product.where(name1: "Sulfarim Powder").update_all(industry_code: "4690")
    Product.where(name1: "Baytril").update_all(industry_code: "4690")
    Product.where(name1: "Trimixin 480").update_all(industry_code: "4690")
    Product.where(name1: "Neosun Soluble Powder 50%").update_all(industry_code: "4690")
    Product.where(name1: "Mycostatin-20").update_all(industry_code: "4690")
    Product.where(name1: "Lucarotin 10%").update_all(industry_code: "4690")
    Product.where(name1: "TMP/S-400").update_all(industry_code: "4690")
    Product.where(name1: "Florcol Premix Power").update_all(industry_code: "4690")
    Product.where(name1: "PACOM").update_all(industry_code: "4690")
    Product.where(name1: "Dung").update_all(industry_code: "4690")
    Product.where(name1: "Wheat Pollard").update_all(industry_code: "4690")
    Product.where(name1: "Corn Powder").update_all(industry_code: "4690")
    Product.where(name1: "Dried Spent Grain").update_all(industry_code: "4690")
    Product.where(name1: "Fish Meal 60%").update_all(industry_code: "4690")
    Product.where(name1: "Full Fat Soybean Meal").update_all(industry_code: "4690")
    Product.where(name1: "Hifat Canola Meal").update_all(industry_code: "4690")
    Product.where(name1: "Lime Stone Grit").update_all(industry_code: "4690")
    Product.where(name1: "Lime Stone Powder").update_all(industry_code: "4690")
    Product.where(name1: "Maize").update_all(industry_code: "4690")
    Product.where(name1: "MDCP 21%").update_all(industry_code: "4690")
    Product.where(name1: "MDCP 22%").update_all(industry_code: "4690")
    Product.where(name1: "N100 (Dabomb-P)").update_all(industry_code: "4690")
    Product.where(name1: "Oil").update_all(industry_code: "4690")
    Product.where(name1: "Poultry Layer Feed").update_all(industry_code: "4690")
    Product.where(name1: "Rice Bran").update_all(industry_code: "4690")
    Product.where(name1: "Rice Powder").update_all(industry_code: "4690")
    Product.where(name1: "Salt").update_all(industry_code: "4690")
    Product.where(name1: "Soybean Hull").update_all(industry_code: "4690")
    Product.where(name1: "Soybean Meal Hi Pro").update_all(industry_code: "4690")
    Product.where(name1: "Soybean Meal Low Pro").update_all(industry_code: "4690")
    Product.where(name1: "Wheat Brans").update_all(industry_code: "4690")
    Product.where(name1: "CHOLINE CHLORIDE 50% SILICA").update_all(industry_code: "4690")
    Product.where(name1: "Bioplex ").update_all(industry_code: "4690")
    Product.where(name1: "Meriden Fusion Dyad").update_all(industry_code: "4690")
    Product.where(name1: "Microtech 5000").update_all(industry_code: "4690")
    Product.where(name1: "Biotronic Top 3").update_all(industry_code: "4690")
    Product.where(name1: "Milk Powder").update_all(industry_code: "4690")
    Product.where(name1: "Calibrin z").update_all(industry_code: "4690")
    Product.where(name1: "Cholin-H").update_all(industry_code: "4690")
    Product.where(name1: "Arbocel RC Fine").update_all(industry_code: "4690")
    Product.where(name1: "Avimix Pan-Cure").update_all(industry_code: "4690")
    Product.where(name1: "Bact-A-Cid").update_all(industry_code: "4690")
    Product.where(name1: "Sodium Bicarbonate").update_all(industry_code: "4690")
    Product.where(name1: "eXOLUTION").update_all(industry_code: "4690")
    Product.where(name1: "Escent").update_all(industry_code: "4690")
    Product.where(name1: "Racto-80").update_all(industry_code: "4690")
    Product.where(name1: "P.Vitamin Con-528").update_all(industry_code: "4690")
    Product.where(name1: "Nystatin").update_all(industry_code: "4690")
    Product.where(name1: "L-Lysine").update_all(industry_code: "4690")
    Product.where(name1: "LTHREONINE").update_all(industry_code: "4690")
    Product.where(name1: "L-Tryptophan Feed Grade").update_all(industry_code: "4690")
    Product.where(name1: "Carbovet T").update_all(industry_code: "4690")
    Product.where(name1: "Lutamix 8188").update_all(industry_code: "4690")
    Product.where(name1: "Trace Min 3806").update_all(industry_code: "4690")
    Product.where(name1: "Gladron Poutry-Min").update_all(industry_code: "4690")
    Product.where(name1: "Globatiox").update_all(industry_code: "4690")
    Product.where(name1: "Grainphos 5000 Powder").update_all(industry_code: "4690")
    Product.where(name1: "Grobig").update_all(industry_code: "4690")
    Product.where(name1: "Dl-Meth").update_all(industry_code: "4690")
    Product.where(name1: "Premix Pig Starter").update_all(industry_code: "4690")
    Product.where(name1: "Premix Pig Breeder").update_all(industry_code: "4690")
    Product.where(name1: "Premix Pig Finisher").update_all(industry_code: "4690")
    Product.where(name1: "Agita 1GB").update_all(industry_code: "4690")
    Product.where(name1: "Gumboro D78").update_all(industry_code: "4690")
    Product.where(name1: "Diftosec").update_all(industry_code: "4690")
    Product.where(name1: "Olvac A+B+HG").update_all(industry_code: "4690")
    Product.where(name1: "Ma5+Clone 30").update_all(industry_code: "4690")
    Product.where(name1: "Coryza Oil").update_all(industry_code: "4690")
    Product.where(name1: "IBNDKILL").update_all(industry_code: "4690")
    Product.where(name1: "ILT").update_all(industry_code: "4690")
    Product.where(name1: "Castran").update_all(industry_code: "4690")
    Product.where(name1: "First Aid Blue").update_all(industry_code: "4690")
    Product.where(name1: "Intrafer-200").update_all(industry_code: "4690")
    Product.where(name1: "Iodine").update_all(industry_code: "4690")
    Product.where(name1: "BTS").update_all(industry_code: "4690")
    Product.where(name1: "Lutalyse").update_all(industry_code: "4690")
    Product.where(name1: "Oxytocin").update_all(industry_code: "4690")
    Product.where(name1: "Betamox LA").update_all(industry_code: "4690")
    Product.where(name1: "Paracetamol BP98").update_all(industry_code: "4690")
    Product.where(name1: "PG 600").update_all(industry_code: "4690")
    Product.where(name1: "B-Complex").update_all(industry_code: "4690")
    Product.where(name1: "Taktic").update_all(industry_code: "4690")
    Product.where(name1: "Duphafral Ade Forte").update_all(industry_code: "4690")
    Product.where(name1: "Baycox").update_all(industry_code: "4690")
    Product.where(name1: "Ingelvac Circoflex").update_all(industry_code: "4690")
    Product.where(name1: "Rhiniffa").update_all(industry_code: "4690")
    Product.where(name1: "Geskypur").update_all(industry_code: "4690")
    Product.where(name1: "Parvoject").update_all(industry_code: "4690")
    Product.where(name1: "Akipor").update_all(industry_code: "4690")
    Product.where(name1: "Retired Layer").update_all(industry_code: "4690")
    Product.where(name1: "Cooper Bind").update_all(industry_code: "4690")
    Product.where(name1: "Toxin Binder").update_all(industry_code: "4690")
    Product.where(name1: "Vectormune FP MG").update_all(industry_code: "4690")
    Product.where(name1: "VTM HVT-NDV").update_all(industry_code: "4690")
    Product.where(name1: "Ingelvac Mycoflex").update_all(industry_code: "4690")
    Product.where(name1: "Aftopor").update_all(industry_code: "4690")
    Product.where(name1: "Ingelvac PRRS MLV").update_all(industry_code: "4690")
    Product.where(name1: "Pestiffa FL").update_all(industry_code: "4690")
    Product.where(name1: "Needle").update_all(industry_code: "4690")
    Product.where(name1: "Norodine 24").update_all(industry_code: "4690")
    Product.where(name1: "Note").update_all(industry_code: "4690")
    Product.where(name1: "Entril 20").update_all(industry_code: "4690")
    Product.where(name1: "Phosphor Mega 5000").update_all(industry_code: "4690")
    Product.where(name1: "Poly").update_all(industry_code: "4690")
    Product.where(name1: "Ritavit H2(Spray Dried Biotin 2%)").update_all(industry_code: "4690")
    Product.where(name1: "Vit-Para").update_all(industry_code: "4690")
    Product.where(name1: "Fercobsang").update_all(industry_code: "4690")
    Product.where(name1: "Hinatiamun 200").update_all(industry_code: "4690")
    Product.where(name1: "Alum").update_all(industry_code: "4690")
    Product.where(name1: "Duphalyte Injection").update_all(industry_code: "4690")
    Product.where(name1: "Herbicite").update_all(industry_code: "4690")
    Product.where(name1: "Diluent").update_all(industry_code: "4690")
    Product.where(name1: "Cofacalcium").update_all(industry_code: "4690")
  end
end
    